### ISSUE TITLE
Pre-release

### ISSUE THREAD

**Issue by baimafeima** [parlr/ruby-font-creator#6]
This is one of the most exciting Chinese font projects at the moment. Is it possible to get a pre-release to see how the project is progressing and to add some screenshots on Github?

**Comment by edouard-lopez** [comment]
@baimafeima thanks, I hadn't had time to work on this for a while. As soon as I start I will update the doc and put some screenshots.

**Comment by baimafeima** [comment]
Thanks for your quick response. I appreciate your efforts. This is a huge undertaking.

**Comment by DaWy** [comment]
I'm also following this closely. Waiting for the pre-release, as I couldn't compile one from myself.

**Comment by edouard-lopez** [comment]
Hello,
The first _Hanzi Pinyin Font_ [pre-release –Nihao-你好– is available](https://github.com/parlr/hanzi-pinyin-font/releases/tag/v0.1.0) : a font to display pinyin on top of the character.

Please [give feedback on `ruby-font-creator`](https://github.com/parlr/ruby-font-creator/issues) repository.

---

cc @DaWy @baimafeima @leebivip @angusshire @SamuelAvO @yangzhao3d @pffy @garnierclement @thomaslefloch

**Comment by baimafeima** [comment]
@edouard-lopez Could you also make ruby-font-creator available via versioned tarballs here on GitHub?

**Comment by edouard-lopez** [comment]
@baimafeima if you look for the font, they have [their own repo](https://github.com/parlr?utf8=%E2%9C%93&q=-font&type=&language=) I will put the font at the root:

* [hanzi-pinyin-font](https://github.com/parlr/hanzi-pinyin-font): TTF or WOFF2
* ~[tifinagh-font](https://github.com/parlr/tifinagh-font)~: need to resume work here

---
**N.B.:** I inverted the dependencies between repos, in order to have each font repository to depend on:

* data: JSON file (or a script to generate one) containing [data to generate the font](https://github.com/parlr/ruby-font-creator/blob/5111c2db95d0c558a7475865001d28351dc92126/README.md#data-structure).  
* ruby-font-creator: script to generate the font

**Comment by baimafeima** [comment]
@edouard-lopez Yeah but I meant that if you make ruby-font-creator itself available as versioned tarballs with a changelog here on GitHub, then it may be considered for inclusion into the repositories of various Linux-based distributions and progress can be tracked by distribution maintainers. I would also appreciate to have a separate issue tracker for the hanzi-pinyin-font. What do you think?

**Comment by edouard-lopez** [comment]
@baimafeima Do you have specific issue to declare on HPF right now? I disable the issue tracker at first to centralize on this repo, and planned to enable them when there is a community.

For the versionning of RFC, that's a good idea, but need to get some time to work on the project again (bit difficult since the birth of my first child :P). See #33

**Comment by edouard-lopez** [comment]
closing as already done
